spring.application.name=RedisTutorial
spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Tutorial;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=Password
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect